In [37]:
%%bash
git 

In [1]:
import torch

import torch.nn as nn
from torch.autograd import Variable
import torch.optim as optim

In [25]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [26]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [27]:
print(y.grad_fn)


In [28]:
z = y * y * 3
out = z.mean()

In [6]:
print(out)

tensor(27., grad_fn=<MeanBackward1>)


In [11]:
z.detach().numpy()

array([[27., 27.],
       [27., 27.]], dtype=float32)

In [12]:
?z.detach

Docstring:
Returns a new Tensor, detached from the current graph.

The result will never require gradient.

.. note::

  Returned Tensor uses the same data tensor as the original one.
  In-place modifications on either of them will be seen, and may trigger
  errors in correctness checks.
Type:      builtin_function_or_method


In [14]:
y.detach().numpy()

array([[3., 3.],
       [3., 3.]], dtype=float32)

## backwardメソッドをあるスカラーにかけることで、 そのスカラーの各パラメータでの偏微分が求まる

In [36]:
out.backward()

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

## 求まった偏微分は各パラメータのほうに格納される

In [30]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

## yは中間生成物なのでgradは存在しない


[Why cant I see .grad of an intermediate variable](https://discuss.pytorch.org/t/why-cant-i-see-grad-of-an-intermediate-variable/94)

一度計算はされているが、メモリー節約のために削除されるとのこと

In [31]:
y.grad

In [33]:
y.requires_grad

True

In [34]:
y.detach()

tensor([[3., 3.],
        [3., 3.]])

In [35]:
y.requires_grad

True

In [ ]:
?